# pixi build instructions (works on linux-64 and linux-aarch64 (arm))
#
# Install pixi via wget-command:
# - wget -qO- https://pixi.sh/install.sh | sh
# - Now restart your terminal or shell to make pixi effective.
#
# Build the software (exclude webots simulato)
# - pixi run build
#

[workspace]
authors = ["Jurge vanEijck <jurge.van.eijck@gmail.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "MRA-components"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[activation]
scripts = ["install/setup.sh"]

[tasks]
refresh = "rm -rf ./log; rm -rf ./build; rm -rf ./install"
build = "colcon build --symlink-install"
test = "colcon test --ctest-args tests"
test_results = "colcon test-result --all --verbose"
# set RMW_IMPLEMENTATION="rmw_cyclonedds_cpp" : solve 1 second init delay by switching to CycloneDDS
#sim = { cmd= "ros2 launch simulation launch.py num_robots_team_A:=5 num_robots_team_B:=5 timeout:=10", env = { RMW_IMPLEMENTATION= "rmw_cyclonedds_cpp"} }


[dependencies]
colcon-common-extensions = ">=0.3.0,<0.4"
compilers = ">=1.9.0,<2"
make = ">=4.4.1,<5"
ninja = ">=1.13.0,<2"
pkg-config = ">=0.29.2,<0.30"
ros-humble-ament-cmake-auto = ">=1.3.11,<2"
ros-humble-ament-cmake-clang-format = ">=0.12.11,<0.13.0"
ros-humble-ament-lint-auto = ">=0.12.11,<0.13"
ros-humble-builtin-interfaces = ">=1.2.1, <1.3"
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-geometry-msgs = ">=4.2.4,<4.3.0"
ros-humble-rosidl-default-generators = ">=1.2.0, <1.3.0"
ros-humble-rosidl-default-runtime = ">=1.2.0, <1.3.0"
ros-humble-rclcpp = ">=16.0.11,<17"
ros-humble-pluginlib = ">=5.1.0,<6"
ros-humble-rmw-cyclonedds-cpp = ">=1.3.4,<2"
ros-humble-ament-cmake-python = ">=1.3.11,<2"
cmake = "3.26.*"


