# pixi build instructions (works on linux-64 and linux-aarch64 (arm))
#
# Install pixi via wget-command:
# - wget -qO- https://pixi.sh/install.sh | sh
# - Now restart your terminal or shell to make pixi effective.
#
# Build the software (exclude webots simulato)
# - pixi run build
#

[workspace]
authors = ["Jurge vanEijck <jurge.van.eijck@gmail.com>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "MRA-components"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[activation]
scripts = ["install/setup.sh"]

[tasks]
refresh = "rm -rf ./log; rm -rf ./build; rm -rf ./install"
build = "colcon build --symlink-install"
test = "colcon test --ctest-args tests"
test_results = "colcon test-result --all --verbose"
test-all = "colcon test --ctest-args tests;colcon test-result --all --verbose"

uncrustify = {cmd = "ament_uncrustify --reformat {{ FILENAME }}", args = [{ arg="FILENAME" }]}
# set RMW_IMPLEMENTATION="rmw_cyclonedds_cpp" : solve 1 second init delay by switching to CycloneDDS
#sim = { cmd= "ros2 launch simulation launch.py num_robots_team_A:=5 num_robots_team_B:=5 timeout:=10", env = { RMW_IMPLEMENTATION= "rmw_cyclonedds_cpp"} }

[dependencies]
compilers = ">=1.11.0,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
make = ">=4.4.1,<5"
ninja = ">=1.13.2,<2"
pkg-config = ">=0.29.2,<0.30"
ros-jazzy-ament-cmake-auto = ">=2.5.6,<3"
ros-jazzy-ament-cmake-clang-format = ">=0.17.5,<0.18"
ros-jazzy-ament-lint-auto = ">=0.17.5,<0.18"
ros-jazzy-builtin-interfaces = ">=2.0.3,<3"
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-geometry-msgs = ">=5.3.7,<6"
ros-jazzy-rosidl-default-generators = ">=1.6.0,<2"
ros-jazzy-rosidl-default-runtime = ">=1.6.0,<2"
ros-jazzy-rclcpp = ">=28.1.18,<29"
ros-jazzy-pluginlib = ">=5.4.5,<6"
ros-jazzy-rmw-cyclonedds-cpp = ">=2.2.3,<3"
ros-jazzy-ament-cmake-python = ">=2.5.6,<3"
cmake = ">=4.4.0,<5"
cppcheck = ">=2.21.0,<3"

