cc_library(
    name = "ruckig",
    hdrs = glob(["ruckig/include/ruckig/*.hpp"]),
    srcs = [
        "ruckig/src/ruckig/brake.cpp",
        "ruckig/src/ruckig/position_first_step1.cpp",
        "ruckig/src/ruckig/position_first_step2.cpp",
        "ruckig/src/ruckig/position_second_step1.cpp",
        "ruckig/src/ruckig/position_second_step2.cpp",
        "ruckig/src/ruckig/position_third_step1.cpp",
        "ruckig/src/ruckig/position_third_step2.cpp",
        "ruckig/src/ruckig/velocity_second_step1.cpp",
        "ruckig/src/ruckig/velocity_second_step2.cpp",
        "ruckig/src/ruckig/velocity_third_step1.cpp",
        "ruckig/src/ruckig/velocity_third_step2.cpp" 
    ],
    includes = ["ruckig/include"],
    copts = [""],
    visibility = ["//visibility:public"],
)

