= LocalBallTracking Robotsports Variant

== Summary

LocalBallTracking is an component that tracks the ball position based on measurements. 

== Scope and context

This variant is RobotSport variant of local ball tracking. 
The original code is written by: Rene van de Molengraft (TechUnited), March, 2008


== Interface details

* **purpose**: track the ball with local sensors
* **inputs**: See link:./interface/Input.proto[Input.proto] for the exact definition.
    ** BallCandidates  

* **outputs**:  See link:./interface/Output.proto[Output.proto] for the exact definition.  
    ** ball position

* *parameters*:  
The component has some configuration parameters.  These parameters are specific for this variant., 
see link:./interface/Params.proto[Params.proto] and 
link:./interface/DefaultParams.json[DefaultParams.json].

== Design

Calculate location of the ball based on the measurements (Sequential Clustering algorithm)

Inspired by Schubert & Sidenblath, Sequential clustering with particle filters - Estimating the number of clusters from data, Proc. 8th Int. Conf. Information Fusion, 2005

Instead of using a particle filter, a discrete filter to the set of hypotheses is applies, which is of itself already a discrete stochast.

As the ball is likely to move,  a constant-velocity model-based Kalman filter is used to estimate the state of the ball.

Note: The component has own internal state data administration and does not store it a protobuf state structure.
It is not following the MSL Reference Architecture as intended. 


== History

Used by Robotsports since 2013, started as a copy of TechUnited's ball tracking algorithm

* March, 19th, 2008, added bound checking and error handling
* February, 13th, 2009, adapted for sorted measurements with varying time interval in between (kalman_update) added object labeling on creation of new object
* May, 8th, 2011, adapted for ball model
* May, 13th, 2011, assume a single ball; removed all book keeping for multiple objects
* June, 26th, 2011, exchanged recursive Kalman filter for batch-wise least-squares estimator (integral formulation)
* May, 20th, 2012, smooth free/non-free transition and kick-aware speed estimation

 
