= LocalBallPreprocessor Robotsports Variant

== Summary

LocalBallPreprocessor is an component that preprocesses ball candidates from the local sensors 
(omnivision and frontcamera).  

== Scope and context

The code is limited to filter the ball with ball candidates from an omnivision-camera and frontcamera. 
Extending to other types of measurement is prepared (e.g. Lidar).
 
== Interface details

* **purpose**: track the ball with local sensors
* **inputs**: See link:./interface/Input.proto[Input.proto] for the exact definition.
    ** Omnivision BallCandidates  
    ** Stereo vision BallCandidates  

* **outputs**:  See link:./interface/Output.proto[Output.proto] for the exact definition.  
    ** filtered BallCandidates

* *parameters*:  
The component has some configuration parameters.  These parameters are specific for this variant., 
see link:./interface/Params.proto[Params.proto] and 
link:./interface/DefaultParams.json[DefaultParams.json].

== Design
In this component the provided measured ball candidates are filtered. 
Only the best ball candidates remain.

Currently if there are front camera ball candidates, 
then the ball candidates from omnivision are removed.
