= LocalObstacleTracking Robotsports Variant

== Summary

LocalObstacleTracking is an component that tracks objects (robots) position based on measurements. 
Poses are using the Field Coordinate System, therefore is not necessary to correct for own movements 
between the ticks when tracking an object multiple ticks. 

== Scope and context

This variant is RobotSport variant of local obstacle tracking. 
The original code is written by: Rene van de Molengraft (TechUnited), March, 2008


== Interface details

* **purpose**: track objects with local sensors
* **inputs**: See link:./interface/Input.proto[Input.proto] for the exact definition.
    ** Obstacle Candidates  

* **outputs**:  See link:./interface/Output.proto[Output.proto] for the exact definition.  
    ** Tracked Obstacles

* *parameters*:  
The component has some configuration parameters.  These parameters are specific for this variant., 
see link:./interface/Params.proto[Params.proto] and 
link:./interface/DefaultParams.json[DefaultParams.json].

== Design

Calculate location of the objects based on the measurements (Sequential Clustering algorithm)

Inspired by Schubert & Sidenblath, Sequential clustering with particle filters - Estimating the number of clusters from data, Proc. 8th Int. Conf. Information Fusion, 2005

Instead of using a particle filter, a discrete filter to the set of hypotheses is applies, which is of itself already a discrete stochast.

As a object is likely to move,  a constant-velocity model-based Kalman filter is used to estimate the states of the obstacle.


Note: The component has own internal state data administration and does not store it a protobuf state structure.
It is not following the MSL Reference Architecture as intended. 
NOTE: positions are directly fed through (not estimated)! Velocities are estimated.

== History

Used by Robotsports since 2013, started as a copy of TechUnited's obstacle tracking algorithm

* March, 19th, 2008, added bound checking and error handling
* February, 13th, 2009, adapted for sorted measurements with varying time interval in between (kalman_update) added object labeling on creation of new object


 
