== Standard Data Definitions

The choice for ROS2 implies to use as much as ROS2 default definitions and widely used concepts as possible.


* link:https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Parameters/Understanding-ROS2-Parameters.html[Parameters] #TODO#

* link:https://docs.ros.org/en/humble/Tutorials/Demos/Logging-and-logger-configuration.html[Logging] #TODO#

* usage of tf2: link:https://docs.ros.org/en/humble/Tutorials/Intermediate/Tf2/Tf2-Main.html[tf2] is the transform library that maintains a hierarchical, time-buffered tree of coordinate frames, allowing robots to track and transform points, vectors, and poses between any two frames (e.g., base, head, gripper, world) within a robotic system.
Including:
** REP-0103 - Standard Units of Measure and Coordinate Conventions (more info: link:https://www.ros.org/reps/rep-0103.html[REP-0103])
** REP-0105 - Coordinate Frames for Mobile Platforms (more info:  link:https://www.ros.org/reps/rep-0105.html[REP-0105])
** REP-0120 - Coordinate Frames for Humanoid Robots (more info: link:https://www.ros.org/reps/rep-0120.html[REP-0120])

[#Pose]
=== Pose
Poses are defined in 6-DOF (x, y, z, rx, ry, rz)
using a right hand coordinate system

* x: positive direction is forwards from the middle of an object
* y: positive direction is leftwards from the middle of an object
* z: positive direction is upwards from the middle of an object
* rx: rotation around x-axis. positive direction is from y-axis to z-axis. Sometimes also called: phi-x or pitch (aircraft principal axis)
* ry: rotation around y-axis. positive direction is from x-axis to z-axis. Sometimes also called: phi-y or roll (aircraft principal axis)
* rz: rotation around z-axis. positive direction is from x-axis to y-axis. Sometimes also called: phi or phi-z or yaw (aircraft principal axis)

=== Velocity
Velocity is defined in 6-DOF, similar to the <<Pose>>.

=== Set piece
A carefully organized and practised move in a team game by which the ball is returned to play. Examples are free kicks, goal kicks, corners, penalties, and throw-ins.  (more on: link:https://en.wikipedia.org/wiki/Set_piece_(football)[wikipedia: set piece (football)])
