@startuml Basic Sample
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person_Ext(main_referee, "Main Referee", $sprite="person")
Person_Ext(refbox_referee, "Refbox Referee", $sprite="person")
Person(developer, "Robotics Engineeer", $sprite="person")


System_Boundary(Referee_system, "Referee Computer") {
    SystemDb_Ext(hl_logging, "HL logging")
    System_Ext(refbox, "Refbox")
}

System_Boundary(hlra_sideline, "HLRA Sideline Software")  {
    System(ui, "User Interface")
    System(visualisation, "Visualisation")
}

System_Boundary(robot, "Robot")  {
    System(hlra, "HLRA robot software", $sprite="robot")
}

System_Ext(teammate, "HLRA teammate", $sprite="robot")


Rel_D(refbox_referee, refbox, "refbox commands")
Rel_D(refbox, ui, "refbox commands")

Rel_D(ui, hlra, "commands")
Rel_D(ui, hlra, "service requests")
Rel_D(ui, hlra, "settings")
Rel_U(hlra, ui, "robot_data", $tags="broadcast")
Rel_D(hlra, visualisation, "robot_data", $tags="broadcast")
Rel_U(hlra, hl_logging, "HL logging", $tags="broadcast")
BiRel_R(hlra, teammate, "robot_data", $tags="broadcast")

Rel_R(main_referee, refbox_referee, "instruct")
Rel(developer, ui, "")
Rel(developer, visualisation, "")
@enduml